server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: @profileActive@
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
    # date统一返回时间戳
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    #直接显示日期时，时区转换
    date-format: yyyy-MM-dd,yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml
  typeAliasesPackage: com.cf.parking.dao.po
  config-location: classpath:/mybatis-config.xml
  global-config:
    sql-parser-cache: true
    refresh: true
    

logging:
  level:
    org.redisson.connection.DNSMonitor: error
    org.apache.http.wire: error
    com.cf.parking: debug


knife4j:
  production: true
